version: '3'
services:
  mdm-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "7777:7777"
    volumes:
      - type: bind
        source: .
        target: /workspace
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Allow access to all available GPUs (adjust as needed)
    command: python app.py --port 7777
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery --app app.celery worker --loglevel=info --pool=solo
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - .:/workspace
    depends_on:
      - redis
      - mdm-web

  redis:
    image: "redis:alpine"
