version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    volumes:
      - type: bind
        source: .
        target: /workspace
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Allow access to all available GPUs (adjust as needed)
    command: python app.py --port "${SERVICE_PORT}"
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery --app app.celery worker --loglevel=info --pool=solo
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - .:/workspace
    depends_on:
      - redis
      - web

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token "${CLOUDFLARED_TOKEN}"
    restart: unless-stopped

  redis:
    image: "redis:alpine"
 
