version: '3'
services:
  mdm:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"  # Map the Jupyter Notebook port
    volumes:
      - type: bind
        source: .
        target: /workspace
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Allow access to all available GPUs (adjust as needed)
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--no-browser", "--NotebookApp.token="]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]